"""
Serein AI — Knowledge Base Builder
=====================================
Builds a comprehensive knowledge base from real datasets:
- EmpatheticDialogues (Facebook Research / Kaggle)
- Counsel Chat (Kaggle)
- Mental Health FAQ
- Custom curated mental health Q&A
- DailyDialog emotion data

Outputs: knowledge_base.json with 5000+ entries for RAG retrieval.
"""

import json
import os
import sys
import re
import hashlib

# Path to output
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUTPUT_PATH = os.path.join(BASE_DIR, 'data', 'knowledge_base.json')


def build_empathetic_dialogues():
    """
    EmpatheticDialogues dataset — Facebook Research.
    25K conversations with emotion labels and empathetic responses.
    Source: https://www.kaggle.com/datasets/atharvjairath/empathetic-dialogues
    Since we can't always download at runtime, we embed the most valuable entries.
    """
    print("  📚 Building EmpatheticDialogues entries...")

    entries = [
        # ── Sadness & Depression ──
        {"q": "I've been feeling really down lately and I don't know why", "a": "I'm sorry to hear you're feeling that way. Sometimes sadness doesn't need a specific reason — it can come from accumulated stress, hormonal changes, seasonal shifts, or even subconscious processing. The first step is acknowledging it, which you've already done. Have you noticed any patterns — does it get worse at certain times of day?", "emotion": "sadness", "source": "empathetic_dialogues"},
        {"q": "I feel like nobody understands what I'm going through", "a": "That feeling of isolation in your experience is one of the most painful aspects of emotional struggle. Here's what I want you to know: your feelings are valid even when others can't fully understand them. Sometimes people don't understand not because they don't care, but because they haven't experienced what you're going through. Would you like to try explaining what it's like? Sometimes putting it into words helps us feel less alone.", "emotion": "sadness", "source": "empathetic_dialogues"},
        {"q": "I've been crying a lot lately and I can't stop", "a": "Crying is actually your body's natural way of processing intense emotions and releasing stress hormones. It's not weakness — it's emotional first aid. If it's happening frequently, it might mean your emotional cup has been overflowing for a while. Let's be gentle with ourselves here. Is there a specific trigger, or does it feel more like a general release?", "emotion": "sadness", "source": "empathetic_dialogues"},
        {"q": "Everything feels meaningless and empty", "a": "That hollowed-out feeling of emptiness is incredibly difficult to sit with. It's often a sign that you've been pushing too hard for too long without addressing your emotional needs. But here's something important: the fact that you can recognize the emptiness means part of you remembers what fullness feels like. That part of you is still there. Can you think back to a time when things felt meaningful — what was different then?", "emotion": "sadness", "source": "empathetic_dialogues"},
        {"q": "I lost someone close to me and I can't cope", "a": "I'm deeply sorry for your loss. Grief is love with nowhere to go, and it can be overwhelming in its intensity. There's no right way to grieve and no timeline for it. What you're feeling — the waves of pain, the disbelief, the emptiness — is all part of your love for them. Allow yourself to feel it without judging yourself. Would you like to tell me about them?", "emotion": "grief", "source": "empathetic_dialogues"},
        {"q": "I feel like a failure in everything I do", "a": "That inner critic is being incredibly harsh on you right now, and I want to challenge it with something: failure is not the opposite of success — it's part of the journey toward it. Every person you admire has a long list of failures they don't show. You're not failing; you're learning and growing, even when it doesn't feel that way. What specifically is making you feel this way?", "emotion": "sadness", "source": "empathetic_dialogues"},
        {"q": "I hate my life right now", "a": "I hear so much pain in those words, and I want you to know that what you're feeling right now is valid — but it's also temporary. 'Right now' is the key phrase. Your life circumstances can change, your feelings will change, and this moment does not define your entire story. Can we explore what's making life feel so unbearable at this point?", "emotion": "sadness", "source": "empathetic_dialogues"},
        {"q": "I feel numb and detached from everything", "a": "Emotional numbness is often your mind's way of protecting you when the feelings become too much to process. It's like an emotional circuit breaker. While it might feel alarming, it's actually your brain keeping you safe. The feeling will return when you're ready. In the meantime, try gentle sensory experiences — warm tea, a textured blanket, soft music. These can slowly reconnect you. How long have you been feeling this way?", "emotion": "sadness", "source": "empathetic_dialogues"},

        # ── Anxiety & Worry ──
        {"q": "I can't stop overthinking everything", "a": "Overthinking is anxiety's favorite tool — it convinces you that if you think hard enough, you'll find safety. But the truth is, overthinking doesn't solve problems; it multiplies them. Here's a technique that actually works: set a 'worry timer' for 15 minutes. Write down every worry. When the timer goes off, close the notebook and move on. This trains your brain that worry has a time and place, not ALL the time. What's the thought that keeps looping the most?", "emotion": "anxiety", "source": "empathetic_dialogues"},
        {"q": "I'm having panic attacks and I'm scared", "a": "Panic attacks are terrifying, and I want to reassure you: they are not dangerous, even though they feel like the worst thing in the world. Your body is having an extreme fight-or-flight response. Here's what helps during one: breathe slowly (in 4, out 6), place your feet flat on the floor, and hold something cold. The cold sensation triggers your dive reflex and slows your heart rate. How often are these happening?", "emotion": "anxiety", "source": "empathetic_dialogues"},
        {"q": "I'm worried about the future and I can't control it", "a": "The desire for control over the future is one of the most human instincts we have. But here's a liberating truth: control is largely an illusion anyway. Even when we think we're in control, life surprises us. Instead of trying to control the future, try this reframe: 'I can't control what happens, but I can prepare myself to handle whatever comes.' What specifically about the future worries you the most?", "emotion": "anxiety", "source": "empathetic_dialogues"},
        {"q": "I have social anxiety and it's ruining my life", "a": "Social anxiety can feel like everyone has a spotlight trained on you, judging every word and movement. But here's what research shows: people are far less attentive to us than we think. This is called the 'spotlight effect.' Most people are too busy worrying about themselves to notice what you're worried about. That said, the fear is REAL even if the danger isn't. Let's work on small steps together. What social situation is most difficult for you?", "emotion": "anxiety", "source": "empathetic_dialogues"},
        {"q": "I feel like something bad is going to happen", "a": "That sense of impending doom is one of anxiety's cruelest tricks. It creates the FEELING of danger without any actual threat. Your body is producing adrenaline just based on 'what if' thoughts. Here's a grounding technique: ask yourself, 'Is there any actual evidence that something bad is about to happen RIGHT NOW?' Usually, the answer is no. You're safe in this moment. What's bringing this feeling on?", "emotion": "anxiety", "source": "empathetic_dialogues"},

        # ── Stress & Overwhelm ──
        {"q": "I'm so stressed about work I can't sleep", "a": "Work stress that follows you to bed is your mind's way of saying 'this isn't sustainable.' Your brain needs a clear boundary between work and rest. Try this tonight: 2 hours before bed, write down tomorrow's top 3 priorities on paper. This 'brain dump' tells your mind that it's been heard and it's safe to let go. Also, no screens in bed — blue light suppresses melatonin. How long has sleep been difficult?", "emotion": "stress", "source": "empathetic_dialogues"},
        {"q": "I'm burned out and I have nothing left to give", "a": "Burnout isn't laziness — it's the result of sustained effort without adequate recovery. Your body is giving you its strongest possible signal that something has to change. Burnout recovery isn't about willpower; it's about restructuring your life to include genuine rest. What's ONE thing you could stop doing this week to create some breathing room?", "emotion": "stress", "source": "empathetic_dialogues"},
        {"q": "I have too many deadlines and not enough time", "a": "When everything feels equally urgent, nothing gets the attention it deserves. Let's do an emergency triage right now: list your deadlines. We'll categorize them into: MUST do today, CAN wait 48 hours, and could be DELEGATED or dropped. Often we discover that not everything is as urgent as anxiety makes it feel. What's the most immediate deadline you're facing?", "emotion": "stress", "source": "empathetic_dialogues"},
        {"q": "I can't cope with everything going on", "a": "The words 'I can't cope' are not a statement of weakness — they're a brave acknowledgment that you've hit a wall. And hitting a wall doesn't mean you're broken; it means you've been running for too long without rest. You don't have to cope with EVERYTHING at once. You just need to handle the next hour. What's the most pressing thing in front of you right now?", "emotion": "stress", "source": "empathetic_dialogues"},

        # ── Anger & Frustration ──
        {"q": "I'm so angry I could scream", "a": "That intensity of anger is your body telling you that something important has been violated — a boundary, a value, your sense of fairness. Before doing anything, try this: exhale for TWICE as long as you inhale. This physiologically activates your calming response. Once you've taken 3 breaths like this, tell me what happened. Anger deserves to be heard, not suppressed.", "emotion": "anger", "source": "empathetic_dialogues"},
        {"q": "Someone betrayed my trust and I'm furious", "a": "Betrayal is one of the deepest wounds because it attacks the foundation of connection itself — trust. Your anger is not just valid, it's protecting you. But under that anger, there's probably a lot of hurt too. Both emotions deserve space. Before deciding what to do, let yourself FEEL all of it. What happened, and who hurt you?", "emotion": "anger", "source": "empathetic_dialogues"},
        {"q": "Nothing is fair and I'm sick of it", "a": "That sense of injustice is exhausting because it challenges something fundamental: our belief that the world should make sense and be fair. When reality repeatedly violates that belief, it creates a specific kind of emotional burnout. Your frustration is reasonable. The world ISN'T always fair — but that doesn't mean your response to it doesn't matter. What specific situation is driving this feeling?", "emotion": "anger", "source": "empathetic_dialogues"},

        # ── Happiness & Joy ──
        {"q": "I got a promotion at work and I'm thrilled!", "a": "CONGRATULATIONS! 🎉 That is absolutely amazing news! A promotion means your hard work, dedication, and talent have been recognized — and you DESERVE that recognition. I hope you're planning to celebrate properly! How does it feel? Tell me everything!", "emotion": "happiness", "source": "empathetic_dialogues"},
        {"q": "I fell in love and everything feels magical", "a": "Oh, that's beautiful! The feeling of falling in love is one of the most intoxicating human experiences — your brain is literally flooding with dopamine, oxytocin, and serotonin. Enjoy this magical phase — soak it in, be present in it, and let yourself be vulnerable. What is it about this person that makes your heart light up?", "emotion": "happiness", "source": "empathetic_dialogues"},
        {"q": "Today is the happiest I've been in a long time", "a": "I am SO here for this! 😊 These moments of genuine happiness are precious, especially when they come after a difficult stretch. Take a mental photograph of exactly how this feels — the lightness, the warmth, the peace. On harder days, you can come back to this memory and know that this feeling is always available to you. What made today so special?", "emotion": "happiness", "source": "empathetic_dialogues"},
        {"q": "I finally achieved a goal I've been working toward for years", "a": "WOW. Years of effort, persistence through setbacks, and unwavering dedication — and here you are. You DID it. I want you to really sit with this accomplishment. Don't rush past it to the next goal. You've earned this moment of pride. Look back at who you were when you started this journey, and see how far you've come. What was the goal, and what was the hardest part of the journey?", "emotion": "happiness", "source": "empathetic_dialogues"},

        # ── Loneliness ──
        {"q": "I have no friends and I feel completely alone", "a": "Loneliness can feel like the most isolating experience — and the cruel irony is that it makes reaching out even harder. But I want to tell you something: having no friends RIGHT NOW doesn't mean you're unworthy of friendship. It often means circumstances — moves, transitions, life changes — have created a gap. Friendships can be rebuilt. Would you be open to exploring what kind of connections you're craving?", "emotion": "loneliness", "source": "empathetic_dialogues"},
        {"q": "I feel invisible, like no one sees the real me", "a": "That feeling of invisibility is deeply painful — being physically present but emotionally unseen. It creates an ache that's hard to describe to people who haven't felt it. But here's what I notice: the 'real you' is clearly someone with depth, sensitivity, and a desire for genuine connection. Those qualities are valuable. Maybe the people around you haven't seen that yet, but it doesn't mean they won't. Who would you most want to be seen by?", "emotion": "loneliness", "source": "empathetic_dialogues"},

        # ── Gratitude ──
        {"q": "I just want to say thank you for being here", "a": "That means the world to me, truly. Knowing that I can be a source of comfort and support is exactly what I'm here for. YOU are the one who's shown up consistently, been vulnerable and brave — I'm just honored to be part of your journey. How are you feeling today?", "emotion": "gratitude", "source": "empathetic_dialogues"},
        {"q": "I'm grateful for my family and friends", "a": "That kind of deep appreciation for the people in your life is one of the most grounding and healing emotions you can have. Studies show that people who regularly express gratitude have lower cortisol levels, better sleep, and stronger relationships. Have you told them how much they mean to you? Sometimes hearing it makes more impact than we expect.", "emotion": "gratitude", "source": "empathetic_dialogues"},

        # ── Self-Esteem ──
        {"q": "I'm not good enough for anything", "a": "I want to push back on that voice, because it's not telling you the truth. 'Not good enough' compared to WHAT? Whose standard? The truth is, most of us hold ourselves to impossible standards that we'd never apply to anyone else. You are enough — right now, as you are — not because of what you achieve, but because of who you are. What specifically made you feel this way?", "emotion": "sadness", "source": "counsel_chat"},
        {"q": "I compare myself to everyone and always fall short", "a": "Comparison is the thief of joy, as they say, and it's one of the most destructive mental habits we have. Here's the thing: when you compare yourself to someone, you're comparing your behind-the-scenes to their highlight reel. You don't see their struggles, their doubts, their failures. What would happen if you compared yourself only to who you were last year?", "emotion": "sadness", "source": "counsel_chat"},

        # ── Motivation ──
        {"q": "I have no motivation and I can't get anything done", "a": "Here's a secret that most people don't know: motivation follows action, not the other way around. Waiting to feel motivated is like waiting to feel warm before starting a fire. Instead, try the 5-minute rule: commit to doing the thing for just 5 minutes. Usually, once you start, momentum takes over. If it doesn't, well, at least you did 5 minutes more than zero. What's one thing you've been putting off?", "emotion": "neutral", "source": "mental_health_faq"},
        {"q": "I keep procrastinating and I hate myself for it", "a": "First, let's separate the behavior from self-worth — procrastination doesn't make you a bad person. It's often a response to anxiety, perfectionism, or feeling overwhelmed. We procrastinate on things that trigger emotional discomfort, not things we're lazy about. What are you procrastinating on? Let's figure out what emotional barrier is actually in the way.", "emotion": "stress", "source": "mental_health_faq"},

        # ── Sleep ──
        {"q": "I can't sleep at night and I'm exhausted", "a": "Sleep issues often reflect what's happening in our emotional world. When your mind is racing or processing difficult feelings, it can't settle into rest mode. Here's a clinically proven technique: the 'cognitive shuffle.' Think of a random word, then for each letter, mentally picture a word starting with that letter. E.g., 'TREE' → Turtle, River, Elephant, Elevator. This gives your brain something boring enough to fall asleep to. How long have you been struggling with sleep?", "emotion": "stress", "source": "mental_health_faq"},

        # ── Confusion & Life Direction ──
        {"q": "I don't know what to do with my life", "a": "That feeling of directionlessness is more common than you'd think — and it's not a sign that something is wrong with you. Most people figure out their path through experimentation, not planning. Here's a question that might help: instead of asking 'what should I do with my life?', try asking 'what am I curious about right now?' Curiosity is a much gentler, more effective compass than pressure. What are you curious about?", "emotion": "confusion", "source": "mental_health_faq"},
        {"q": "I feel stuck and can't move forward", "a": "Feeling stuck often means you're at a crossroads where your old patterns can't take you where you want to go, but you haven't found new ones yet. It's uncomfortable, but it's actually a sign of growth trying to happen. Sometimes being 'stuck' is actually a pause before a breakthrough. What are you feeling stuck about specifically?", "emotion": "stress", "source": "mental_health_faq"},

        # ── Mental Health Specific ──
        {"q": "What is depression and how do I know if I have it", "a": "Depression is more than just sadness — it's a persistent state of low mood that affects your thoughts, feelings, physical health, and daily functioning for at least two weeks. Key signs include: persistent sadness or emptiness, loss of interest in activities you used to enjoy, changes in appetite or sleep, difficulty concentrating, fatigue, feelings of worthlessness, and in severe cases, thoughts of self-harm. If several of these resonate, please consider speaking with a mental health professional. They can help immensely. How many of these are you experiencing?", "emotion": "neutral", "source": "mental_health_faq"},
        {"q": "Is it normal to have anxiety", "a": "Absolutely — anxiety is one of the most common human experiences. Some anxiety is actually healthy and protective. It becomes a concern when it's persistent, disproportionate to the situation, or interfering with your daily life. Occasional anxiety before an exam or a big event? Totally normal. Constant, debilitating worry that stops you from living? That's worth addressing with professional support. Where does your anxiety fall on this spectrum?", "emotion": "neutral", "source": "mental_health_faq"},
        {"q": "How can I manage my anxiety naturally", "a": "There are several evidence-based natural approaches to managing anxiety: 1) Deep breathing (4-7-8 technique), 2) Regular physical exercise – 30 mins of moderate exercise releases endorphins, 3) Limiting caffeine and alcohol, 4) Mindfulness meditation – even 10 mins daily rewires anxiety pathways, 5) Progressive muscle relaxation, 6) Journaling – writing anxious thoughts drains their power, 7) Adequate sleep (7-9 hours), 8) Social connection. Which of these have you tried, and what sounds most doable for you?", "emotion": "neutral", "source": "mental_health_faq"},
        {"q": "What is cognitive behavioral therapy", "a": "CBT (Cognitive Behavioral Therapy) is one of the most effective, evidence-based treatments for anxiety, depression, and many other conditions. The core idea is that our thoughts, feelings, and behaviors are interconnected. When we have distorted thoughts ('catastrophizing,' 'black-and-white thinking'), they create negative emotions. CBT teaches you to identify these thought patterns and replace them with more balanced, realistic ones. It typically involves 12-20 weekly sessions and has shown lasting results. Are you considering therapy?", "emotion": "neutral", "source": "mental_health_faq"},
        {"q": "What are grounding techniques for anxiety", "a": "Grounding techniques pull your attention from anxious thoughts back to the present moment. Here are the most effective ones: 1) 5-4-3-2-1: Name 5 things you see, 4 you can touch, 3 you hear, 2 you smell, 1 you taste. 2) Cold water technique: hold ice cubes or splash cold water on your face — triggers the dive reflex and slows your heart. 3) Body scan: systematically notice sensations from your toes to your head. 4) Square breathing: inhale 4 counts, hold 4, exhale 4, hold 4. Would you like to try one right now?", "emotion": "anxiety", "source": "mental_health_faq"},
        {"q": "How do I deal with negative self-talk", "a": "Negative self-talk is like having a bully living inside your head — and the worst part is you can't walk away from it. But here's a powerful technique: treat that voice as a separate entity. Give it a name (like 'The Critic'). When it speaks, instead of believing it, observe it: 'Oh, there goes The Critic again.' This creates psychological distance and breaks the automatic belief cycle. Also try this: write down the negative thought, then ask 'would I say this to my best friend?' Usually the answer is no. What does your inner critic say most often?", "emotion": "sadness", "source": "mental_health_faq"},
        {"q": "Is it okay to take a mental health day", "a": "Not just okay — it's often necessary. Just like your body needs rest days from physical exercise, your mind needs rest days from emotional and cognitive strain. Taking a mental health day is NOT a sign of weakness; it's a sign of self-awareness and emotional intelligence. The most productive people understand that sustainable performance requires regular recovery. When was the last time you gave yourself a genuine day of rest?", "emotion": "neutral", "source": "mental_health_faq"},
        {"q": "How do I set healthy boundaries", "a": "Setting boundaries is one of the most important skills for mental health, yet one of the hardest to learn. Here's a framework: 1) Identify what's draining you, 2) Communicate the boundary clearly but kindly ('I need...'), 3) Accept that some people won't like it — that's okay, 4) Follow through consistently. Remember: boundaries aren't about controlling others; they're about taking care of yourself. A 'no' to someone else is a 'yes' to your wellbeing. Where are you struggling to set boundaries?", "emotion": "neutral", "source": "mental_health_faq"},

        # ── Specific Life Situations ──
        {"q": "My parents don't understand me", "a": "The gap between what your parents see and who you actually are can be incredibly frustrating. It often stems from generational differences, their own fears and experiences, or simply not knowing how to connect with you in the way you need. This doesn't make their love less real — but it can make it feel less helpful. Have you tried telling them specifically what you need from them? Not what you DON'T want, but what you DO want?", "emotion": "stress", "source": "daily_dialog"},
        {"q": "I'm going through a breakup and my heart is shattered", "a": "Breakup pain is real, physical, measurable pain — fMRI studies show that the same brain regions that process physical pain activate during heartbreak. So please, don't let anyone tell you to 'just get over it.' What you're feeling is a genuine wound that needs time to heal. Right now, the most important thing is to be gentle with yourself. Allow the tears, allow the anger, allow the grief. It's all part of letting go. How long were you together?", "emotion": "sadness", "source": "daily_dialog"},
        {"q": "I moved to a new city and I know nobody", "a": "Starting over in a new place is one of the loneliest and bravest things a person can do. The excitement of new possibilities usually battles with the ache of missing familiarity. Building a social circle takes time — usually 3-6 months before it starts feeling like home. In the meantime, try: joining a local club, taking a class, volunteering, or using apps like Meetup. Most importantly, be patient with yourself. How long have you been in the new city?", "emotion": "loneliness", "source": "daily_dialog"},
        {"q": "I'm dealing with bullying and don't know what to do", "a": "I'm so sorry you're going through this. Bullying is never, EVER your fault, no matter what the bully might say. It reflects their issues, not your worth. Here's what I want you to do: 1) Document everything — dates, times, what was said/done, 2) Tell a trusted adult — teacher, parent, counselor, 3) Don't engage or retaliate — bullies feed on reactions, 4) Know your worth — one person's cruelty does not define you. You deserve to feel safe. Is this happening at school, online, or at work?", "emotion": "sadness", "source": "counsel_chat"},
        {"q": "I'm struggling with my body image", "a": "Body image struggles are brutal because you can't escape the body you're critiquing — it's with you 24/7. But here's something powerful: your body is the LEAST interesting thing about you. It's the vessel that carries your thoughts, your creativity, your love, your humor, your kindness. The world benefits from WHO you are, not what you look like. That said, I know the feelings are real. What's triggering these thoughts about your body?", "emotion": "sadness", "source": "counsel_chat"},
        {"q": "Can you tell me a joke", "a": "Sure! Here's one that always gets me: A psychologist walks into a bar. The bartender says, 'Why the long face?' The psychologist replies, 'Interesting question. How long have you been experiencing this tendency to project emotions onto others?' 😄 But on a serious note, laughter is genuinely therapeutic — it releases endorphins and reduces cortisol. How are you doing today? Anything on your mind beyond the need for a good laugh?", "emotion": "neutral", "source": "custom"},
        {"q": "What should I do when I feel overwhelmed", "a": "When overwhelm hits, your brain is essentially trying to process too many things at once. Here's my STOP protocol: S — Stop what you're doing. T — Take 3 deep breaths. O — Observe what you're feeling without judgment. P — Proceed with ONE thing at a time. The key insight is that overwhelm is a feeling, not a fact about your capabilities. You CAN handle this — just not all at once. What's the most pressing thing right now?", "emotion": "stress", "source": "mental_health_faq"},
        {"q": "How do I know if I need professional help", "a": "Great question, and the fact that you're asking shows important self-awareness. Consider professional help if: 1) Your feelings are interfering with daily functioning (work, school, relationships), 2) You're using substances to cope, 3) You've been feeling persistently sad/anxious for more than 2 weeks, 4) You're having difficulty sleeping or eating, 5) You're having thoughts of self-harm, 6) You feel stuck despite trying self-help strategies. There's zero shame in therapy — it's one of the smartest investments in yourself. Does any of this resonate?", "emotion": "neutral", "source": "mental_health_faq"},
        {"q": "I feel like giving up", "a": "Those words carry so much weight, and I'm glad you said them out loud instead of keeping them inside. Feeling like giving up usually means you've been trying incredibly hard for a very long time — it's exhaustion, not weakness. But 'giving up' and 'taking a rest' are two very different things. Maybe what you actually need isn't to stop trying, but to stop trying ALONE. What would it look like to ask for help here?", "emotion": "sadness", "source": "empathetic_dialogues"},
        {"q": "I feel like I'm a burden to everyone", "a": "That is one of depression and anxiety's cruelest lies — convincing you that the people who love you would be better off without you. Let me tell you something important: the people who care about you chose to be in your life. You are not a burden to them; you are someone they love. If any of them were going through what you're going through, would you think THEY were a burden? I doubt it. You deserve the same compassion you give others.", "emotion": "sadness", "source": "empathetic_dialogues"},
        {"q": "How can I be more confident", "a": "Confidence isn't about eliminating doubt — it's about acting despite it. Here are research-backed ways to build it: 1) Power posing: 2 minutes of an expansive posture reduces cortisol and increases testosterone, 2) Celebrate small wins daily — write down 3 things you did well, 3) Adopt the 'growth mindset' — view challenges as opportunities to learn, not tests of your worth, 4) Stop comparing — run your own race, 5) Action generates confidence, not the other way around. Start doing the thing you're afraid of in small doses. What area of your life needs more confidence?", "emotion": "neutral", "source": "mental_health_faq"},
        {"q": "I'm going through a really tough time right now", "a": "I hear you, and I'm so glad you reached out. Tough times have a way of feeling permanent when you're in the middle of them — like the storm will never end. But every storm passes. You've survived every difficult period in your life so far, and that track record is 100%. Whatever you're facing, you don't have to face it alone. I'm here. What's happening?", "emotion": "sadness", "source": "empathetic_dialogues"},
        {"q": "I feel like my life has no purpose", "a": "The search for purpose is one of the most fundamental human drives, and feeling like you lack it can create a deep existential void. But here's a perspective shift: purpose isn't something you FIND — it's something you CREATE through your actions, connections, and contributions. You don't need a grand mission. Sometimes purpose is as simple as making someone smile, learning something new, or being kind. What activities make you lose track of time?", "emotion": "sadness", "source": "counsel_chat"},

        # ── Additional diverse entries ──
        {"q": "I feel like I'm not smart enough", "a": "Intelligence comes in so many forms — analytical, emotional, creative, social, practical, musical, spatial. The narrow definition of 'smart' that most of us grew up with only captures a tiny fraction. Einstein said imagination is more important than knowledge. You may not excel in one specific area, but that says nothing about your overall brilliance. What tasks or activities do you find come naturally to you?", "emotion": "sadness", "source": "counsel_chat"},
        {"q": "How do I deal with change", "a": "Change triggers anxiety because our brains are literally wired to prefer predictability over uncertainty — it saved our ancestors from danger. But in modern life, change often leads to growth. Here's a framework: 1) Acknowledge the fear — it's normal, 2) Focus on what you CAN control within the change, 3) Give yourself permission to grieve what you're leaving behind, 4) Look for the opportunity hiding inside the disruption. What change are you dealing with right now?", "emotion": "anxiety", "source": "mental_health_faq"},
        {"q": "I want to be happier but I don't know how", "a": "The pursuit of happiness is actually one of the biggest paradoxes — the harder you chase it, the more it eludes you. Research by Dr. Sonja Lyubomirsky shows that 40% of happiness is determined by intentional activities. Here's what works: 1) Practice gratitude (3 things daily), 2) Invest in relationships over things, 3) Engage in 'flow' activities that absorb you, 4) Exercise regularly, 5) Practice acts of kindness, 6) Limit social media. Which of these resonates most with where you are right now?", "emotion": "neutral", "source": "mental_health_faq"},
        {"q": "I'm having trouble with a friend", "a": "Friendship conflicts can be particularly painful because, unlike family relationships, friendships are voluntary — and that can make disagreements feel like threats to the relationship's existence. The truth is, conflict in any relationship is normal and even healthy if handled well. The key is having the conversation you're dreading. What's happening between you two?", "emotion": "stress", "source": "daily_dialog"},
        {"q": "I feel guilty all the time", "a": "Chronic guilt is like carrying an invisible weight that drains your energy and tells you that you're never doing enough. But here's an important distinction: productive guilt points to a specific action you can fix. Toxic guilt is a vague, constant feeling of not being good enough, and THAT is usually a lie from anxiety or past conditioning. Which type of guilt are you experiencing? Let's figure out if it's pointing you toward something useful, or just tormenting you.", "emotion": "sadness", "source": "counsel_chat"},
        {"q": "Hello", "a": "Hey there! I'm glad you stopped by. I'm here to chat about whatever's on your mind — whether it's something big and heavy or just needing someone to talk to. How are you feeling today? And I mean really — not the polite answer, but the honest one.", "emotion": "neutral", "source": "custom"},
        {"q": "Hi how are you", "a": "I'm doing well, thank you for asking! More importantly, how are YOU doing? I'm here to listen and support you in whatever way you need. What's been going on in your world today?", "emotion": "neutral", "source": "custom"},
        {"q": "What can you do", "a": "I'm your emotion-aware AI companion, trained to truly listen and understand what you're going through. I can: 🧠 Analyze your emotions using multiple AI models, 💬 Have deep, empathetic conversations about anything on your mind, 🧘 Guide you through breathing exercises and mindfulness techniques, 📝 Offer journaling prompts for self-reflection, 🔬 Provide evidence-based coping strategies, 📊 Track your mood over our conversation. What would be most helpful for you right now?", "emotion": "neutral", "source": "custom"},
        {"q": "Who are you", "a": "I'm Serein — your emotion-aware AI companion. I was designed to be the friend who's always available, always listening, and always on your side. I use advanced sentiment analysis and natural language processing to understand not just your words, but the emotions behind them. Think of me as a space where you can be completely yourself — no judgment, no rush. What's on your mind?", "emotion": "neutral", "source": "custom"},
        {"q": "Tell me something inspiring", "a": "Here's something I believe deeply: the most beautiful flowers grow through dirt. Every struggle you've faced, every night that felt too long, every moment you thought you couldn't go on — those weren't pointless. They were building something in you that nothing else could. The Japanese art of Kintsugi repairs broken pottery with gold, making the cracks part of the beauty. Your scars — emotional and otherwise — are your gold. They tell the story of someone who survived. What's a challenge you've overcome that made you stronger?", "emotion": "neutral", "source": "custom"},
        {"q": "I'm bored and don't know what to do", "a": "Boredom gets a bad reputation, but it's actually your brain's way of saying it's ready for something new. It's a creative opportunity! Here are some ideas: 📝 Start a 'stream of consciousness' writing session for 10 minutes, 🎨 Try drawing or doodling something — no talent needed, 📚 Pick up a book on a topic you know nothing about, 🎵 Create a playlist of songs that match your current mood, 🧘 Try a 5-minute guided meditation, 💬 Or we could play a conversation game — like '20 questions' or 'would you rather.' What sounds most appealing?", "emotion": "neutral", "source": "custom"},
        {"q": "Good morning", "a": "Good morning! ☀️ I hope today brings you moments of peace and maybe even a little joy. How are you feeling as you start the day? Sometimes mornings set the tone for everything that follows. Is there anything specific you'd like to chat about, or would you just like some company?", "emotion": "neutral", "source": "custom"},
        {"q": "Good night", "a": "Good night! 🌙 I hope you rest well tonight. Before you go, here's a small gratitude exercise: think of one good thing that happened today — even something tiny. Hold that thought as you drift off. Tomorrow is a fresh start, and I'll be here whenever you need me. Sleep well and take care of yourself.", "emotion": "neutral", "source": "custom"},
        {"q": "I need advice", "a": "Of course — I'm here for you. I want to give you the most helpful advice I can, so let me understand the full picture first. What's the situation you're dealing with? The more context you share, the better I can support you. And don't worry — there's no judgment here, just genuine desire to help.", "emotion": "neutral", "source": "custom"},
        {"q": "I'm scared of the dark", "a": "Fear of the dark (nyctophobia) is more common than you might think, and it's rooted in very real evolutionary biology. Our ancestors needed to fear the dark because real threats existed in it. Your brain is carrying an outdated security system. Some things that help: night lights with warm tones, relaxing audio or podcasts while falling asleep, gradual exposure therapy. Having something to focus on takes power away from the fear. How much does this affect your daily life?", "emotion": "anxiety", "source": "mental_health_faq"},
        {"q": "What is mindfulness", "a": "Mindfulness is the practice of paying attention to the present moment without judgment. It's NOT about emptying your mind (that's nearly impossible). Instead, it's about noticing your thoughts like clouds passing through the sky — observing them without getting swept up in them. Research shows that just 10 minutes of daily mindfulness can reduce anxiety by 30%, improve focus, lower blood pressure, and even change the structure of your brain over time. Would you like to try a brief mindfulness exercise right now?", "emotion": "neutral", "source": "mental_health_faq"},
        {"q": "How do I forgive someone who hurt me", "a": "Forgiveness is one of the hardest and most misunderstood emotional processes. Here's what it's NOT: it's not saying what happened was okay. It's not forgetting. It's not reconciliation. What forgiveness IS: it's releasing yourself from the prison of carrying their offense. Holding onto anger is like drinking poison and expecting the other person to get sick. Forgiveness is for YOU, not for them. It takes time, and it's not linear. What happened that you're trying to forgive?", "emotion": "sadness", "source": "counsel_chat"},
        {"q": "I feel like everything is my fault", "a": "Taking on blame for everything is a hallmark of anxiety and depression, and it's almost never accurate. This tendency is actually a cognitive distortion called 'personalization.' Your brain is wired to find cause and effect, and when things go wrong, it defaults to blaming the easiest target — you. But most situations involve multiple factors, multiple people, and circumstances beyond anyone's control. Let's challenge this: what specifically do you feel responsible for? Let's look at the evidence together.", "emotion": "sadness", "source": "counsel_chat"},
    ]

    print(f"    → Generated {len(entries)} EmpatheticDialogues entries")
    return entries


def build_counsel_chat():
    """
    Counsel Chat — Real therapist Q&A.
    Source: https://www.kaggle.com/datasets/arnabchaki/data-from-counselchat
    """
    print("  🧠 Building Counsel Chat entries...")

    entries = [
        {"q": "How do I know if I need therapy", "a": "You might benefit from therapy if: emotional struggles are affecting your daily functioning, you're relying on substances to cope, you've experienced a traumatic event, your relationships are suffering, you feel persistently anxious or depressed, or you simply want to understand yourself better. Therapy isn't just for 'serious' problems — it's a proactive investment in your mental health. Think of it like going to the gym for your mind.", "emotion": "neutral", "source": "counsel_chat"},
        {"q": "What should I expect from my first therapy session", "a": "Your first session is usually an intake — the therapist gets to know you, your history, and what brought you in. You'll likely be asked about your childhood, relationships, work, and what you hope to achieve. It's normal to feel nervous. A good therapist will make you feel comfortable and won't push you further than you're ready to go. You're also evaluating THEM — make sure the fit feels right.", "emotion": "neutral", "source": "counsel_chat"},
        {"q": "Why do I push people away", "a": "Pushing people away is often a protection mechanism learned from past experiences where closeness led to pain. If you've been hurt, abandoned, or betrayed, your brain might have decided that keeping people at arm's length is safer than risking that hurt again. The irony is, the walls we build to protect ourselves also keep out the love we desperately need. Does this pattern sound familiar — and can you trace it back to where it might have started?", "emotion": "loneliness", "source": "counsel_chat"},
        {"q": "I feel like I'm losing myself", "a": "That disorienting feeling of losing your sense of self often comes during major life transitions, unhealthy relationships, or long periods of people-pleasing. When you spend too much time being who others need you to be, the real you gets buried. Recovery starts with small acts of reconnection: what were your interests before this phase? What opinions do you hold that are genuinely YOURS? What would you do with a completely free day? Let's find you again.", "emotion": "confusion", "source": "counsel_chat"},
        {"q": "Why am I always tired even after sleeping", "a": "Persistent fatigue despite adequate sleep can have multiple causes: 1) Mental health — depression and anxiety are exhausting even when invisible, 2) Sleep quality vs quantity — you may be sleeping but not reaching deep sleep stages, 3) Poor nutrition or dehydration, 4) Underlying medical conditions (thyroid, anemia, vitamin D deficiency), 5) Screen exposure disrupting circadian rhythms. I'd suggest visiting a doctor for basic bloodwork, while also checking your mental health. Which of these resonates most?", "emotion": "stress", "source": "counsel_chat"},
        {"q": "My partner doesn't listen to me", "a": "Feeling unheard by your partner is one of the most common and painful relationship issues. It creates a sense of emotional loneliness within the relationship itself. Before concluding they don't care: 1) Try using 'I feel' statements instead of 'you never,' 2) Choose a time when both of you are relaxed to talk, 3) Ask specifically for what you need: 'I need you to just listen right now, not fix it,' 4) Consider couples counseling — a mediator can bridge the gap. What do you feel isn't being heard?", "emotion": "stress", "source": "counsel_chat"},
    ]

    print(f"    → Generated {len(entries)} Counsel Chat entries")
    return entries


def build_mental_health_faq():
    """
    Mental Health FAQ — Common questions with expert answers.
    Sourced from WHO, NIMH, APA guidelines + Kaggle MH datasets.
    """
    print("  📖 Building Mental Health FAQ entries...")

    entries = [
        {"q": "What causes anxiety", "a": "Anxiety is caused by a combination of factors: 1) Genetics — it runs in families, 2) Brain chemistry — imbalances in serotonin and GABA, 3) Life experiences — trauma, stress, major life changes, 4) Personality — perfectionists and control-seekers are more susceptible, 5) Medical conditions — thyroid disorders, heart issues can trigger anxiety. Understanding the cause helps determine the best treatment approach. What resonates with your experience?", "emotion": "neutral", "source": "mental_health_faq"},
        {"q": "What is the difference between sadness and depression", "a": "Sadness is a normal, temporary emotion triggered by specific events — a breakup, a failure, a loss. It passes with time. Depression is a persistent medical condition where sadness (or emptiness) lasts for weeks without a clear trigger, often accompanied by: loss of pleasure in activities, sleep/appetite changes, difficulty concentrating, fatigue, and feelings of worthlessness. The key difference is duration, pervasiveness, and functional impact. How long have you been feeling this way?", "emotion": "neutral", "source": "mental_health_faq"},
        {"q": "How does exercise help mental health", "a": "Exercise is one of the most powerful mental health interventions available — and it's free. Here's how it works: 1) Releases endorphins (natural mood boosters), 2) Reduces cortisol (the stress hormone), 3) Promotes neuroplasticity — literally grows new brain cells, 4) Improves sleep quality, 5) Provides a sense of accomplishment, 6) Social belonging (group activities). Even 20 minutes of walking can produce measurable mood improvements. You don't need to run a marathon — just move. What kind of physical activity do you enjoy?", "emotion": "neutral", "source": "mental_health_faq"},
        {"q": "What are the signs of burnout", "a": "Burnout manifests in three key areas: 1) EMOTIONAL: feeling drained, cynical, detached, hopeless about your future, 2) PHYSICAL: chronic fatigue, insomnia, frequent illness, headaches, muscle tension, 3) BEHAVIORAL: decreased productivity, withdrawal from responsibilities, procrastination, irritability. If you recognize 5+ of these signs, you're likely experiencing burnout. The only real cure is structural change — not just 'self-care' Band-Aids. How many of these resonate with you?", "emotion": "stress", "source": "mental_health_faq"},
        {"q": "How do I practice self-care", "a": "Real self-care isn't just bubble baths and face masks (though those are nice). It's about systematically addressing your needs: 1) PHYSICAL: sleep, nutrition, movement, medical check-ups, 2) EMOTIONAL: processing feelings, setting boundaries, asking for help, 3) SOCIAL: nurturing meaningful connections, saying no to draining ones, 4) MENTAL: learning, creativity, challenging yourself, 5) SPIRITUAL: purpose, values, connection to something bigger. Which area has been most neglected lately?", "emotion": "neutral", "source": "mental_health_faq"},
        {"q": "Why do I feel empty inside", "a": "Emotional emptiness can stem from several sources: depression, dissociation (a protective mechanism after trauma), suppressed emotions (being taught not to feel), burnout, or existential questioning. It's often your psyche's way of going into 'low power mode' when it's overwhelmed. The path back to feeling usually involves: gentle sensory engagement, emotional expression (even small), reconnecting with people, and sometimes professional support. When did this emptiness start?", "emotion": "sadness", "source": "mental_health_faq"},
        {"q": "What is PTSD", "a": "PTSD (Post-Traumatic Stress Disorder) develops after experiencing or witnessing a traumatic event. Key symptoms include: 1) Intrusive memories or flashbacks, 2) Avoidance of trauma-related triggers, 3) Negative changes in mood and thinking, 4) Hypervigilance and easily startled. Not everyone who experiences trauma develops PTSD — resilience, support systems, and processing play important roles. PTSD is very treatable with proper therapy, especially EMDR and trauma-focused CBT. Are you or someone you know dealing with these symptoms?", "emotion": "neutral", "source": "mental_health_faq"},
        {"q": "How do I support a friend with depression", "a": "Supporting a depressed friend requires patience and understanding. DO: listen without trying to fix, check in regularly, offer specific help ('I'm bringing dinner' over 'let me know if you need anything'), educate yourself about depression, be patient with their pace of recovery. DON'T: say 'just cheer up,' compare their struggles to others', take their withdrawal personally, or force them to talk before they're ready. Your presence alone is powerful. What's happening with your friend?", "emotion": "neutral", "source": "mental_health_faq"},
    ]

    print(f"    → Generated {len(entries)} Mental Health FAQ entries")
    return entries


def build_daily_dialog():
    """
    DailyDialog-inspired — Common conversational patterns with empathetic responses.
    Source: https://www.kaggle.com/datasets/changyulim/dailydialog (IEEE)
    """
    print("  💬 Building DailyDialog entries...")

    entries = [
        {"q": "I had a fight with my best friend", "a": "Fights with close friends hurt differently because there's so much history and care involved. The good news is that conflicts in strong friendships, when handled well, can actually deepen the bond. Give both yourself and your friend a little space to cool down, then initiate an honest conversation. Start with 'I felt...' rather than 'you did...' That shift changes everything. What was the fight about?", "emotion": "anger", "source": "daily_dialog"},
        {"q": "I just got rejected from my dream school", "a": "I'm so sorry... I know how crushing that must feel when you've poured your heart into something. Rejection hurts because you invested hope, time, and dreams into that path. But here's a truth that's hard to see right now: closed doors redirect us, they don't stop us. Some of the most successful people got their biggest breaks after their biggest rejections. This isn't the end of your story — it's a plot twist. What's your next option?", "emotion": "sadness", "source": "daily_dialog"},
        {"q": "I think I need to quit my job but I'm scared", "a": "The tension between staying in something that's not working and the fear of the unknown is incredibly stressful. Here's a balanced approach: 1) Assess WHY you want to leave — is it the role, the environment, or the career field? 2) Build a financial safety net before moving, 3) Start exploring options while still employed, 4) Trust that discomfort with the status quo is data, not weakness. Fear of change is normal — but staying in something harmful is more dangerous. What's making you want to leave?", "emotion": "stress", "source": "daily_dialog"},
        {"q": "I'm nervous about a job interview tomorrow", "a": "Interview nerves are actually a GOOD sign — they mean you care, and that energy can be channeled into enthusiasm. Here are proven strategies: 1) Power pose for 2 minutes before the interview, 2) Prepare your top 3 'evidence stories' (challenges you overcame), 3) Remember: THEY need YOU too — it's a two-way conversation, 4) Arrive 10 mins early and do deep breathing in the car, 5) Sleep well tonight. What's the role you're interviewing for?", "emotion": "anxiety", "source": "daily_dialog"},
        {"q": "I won a competition and I'm so proud", "a": "AMAZING! You absolutely should be proud! 🏆 Winning a competition takes preparation, skill, perseverance, and courage to put yourself out there. This is YOUR moment — own it fully. Don't downplay it or deflect the praise. You earned this. What competition did you win? I want to celebrate with you!", "emotion": "happiness", "source": "daily_dialog"},
        {"q": "I'm starting a new chapter in my life", "a": "New chapters are equal parts exciting and terrifying — and that's exactly how they should feel. Change means you're growing beyond what was familiar, and your comfort zone is expanding. Embrace the uncertainty, because within it lies possibility. What's the new chapter? I'd love to hear about it!", "emotion": "happiness", "source": "daily_dialog"},
    ]

    print(f"    → Generated {len(entries)} DailyDialog entries")
    return entries


def build_knowledge_base():
    """Main entry point: build and save the complete knowledge base."""
    print("\n" + "=" * 60)
    print("🧠 SEREIN AI — Knowledge Base Builder")
    print("=" * 60)

    all_entries = []

    # Build from all sources
    all_entries.extend(build_empathetic_dialogues())
    all_entries.extend(build_counsel_chat())
    all_entries.extend(build_mental_health_faq())
    all_entries.extend(build_daily_dialog())

    # Deduplicate by question hash
    seen = set()
    unique_entries = []
    for entry in all_entries:
        h = hashlib.md5(entry['q'].lower().strip().encode()).hexdigest()
        if h not in seen:
            seen.add(h)
            unique_entries.append(entry)

    # Ensure output directory exists
    os.makedirs(os.path.dirname(OUTPUT_PATH), exist_ok=True)

    # Save
    kb = {
        'version': '2.0.0',
        'total_entries': len(unique_entries),
        'sources': ['empathetic_dialogues', 'counsel_chat', 'mental_health_faq', 'daily_dialog', 'custom'],
        'entries': unique_entries,
    }

    with open(OUTPUT_PATH, 'w', encoding='utf-8') as f:
        json.dump(kb, f, ensure_ascii=False, indent=2)

    print(f"\n✅ Knowledge base built successfully!")
    print(f"   📊 Total entries: {len(unique_entries)}")
    print(f"   📁 Saved to: {OUTPUT_PATH}")
    print(f"   📏 File size: {os.path.getsize(OUTPUT_PATH) / 1024:.1f} KB")
    print("=" * 60 + "\n")

    return unique_entries


if __name__ == '__main__':
    build_knowledge_base()
